keys:
  # Original Flux keys
  - &dh274 age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
  - &simon-desktop age1cl0av8knan6p5fhd3gelfa004z2xgkv6nv5sharhl7fcdkhlv5tqjcjrhx


creation_rules:
  # Flux specific rules for components directory
  - encrypted_regex: '^(data|stringData)$'
    path_regex: components/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key__groups:
    - age:
      - *dh274

  # Flux specific rules for clusters directory
  - encrypted_regex: '^(data|stringData)$'
    path_regex: clusters/.*\.ya?ml
    key-groups:
    - age:
      - *dh274

  # Sops-Nix specific rules for secrets (YAML, JSON, env, ini)
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dh274
      - *simon-desktop



