keys:
  # Original Flux keys
  - &dh274 age10wjzxqwstyddl6zy02drchuy76a3fph3jznnp8agu5t9gkqjdegsj4a0ls
  - &fablabmuc-38c3-minipc age1y54qgey5kd66rtadzwck29pmu8dz78wgdymkcdf84kpprs5d634qwswgt7


creation_rules:
  # Sops-Nix specific rules for secrets (YAML, JSON, env, ini)
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dh274
      - *fablabmuc-38c3-minipc



