version: "3.3"
name: "traefik-test"
services:

  whoami:
    image: "mendhak/http-https-echo"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entryPoints=websecure"
      - "traefik.http.routers.whoami.tls.certResolver=letsencrypt"
      - "traefik.http.routers.whoami.rule=Host(`whoami.38c3.tschunk.social`)"
      - "traefik.http.routers.whoami.middlewares=oauth2-auth@file"
  whoami2:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.entryPoints=websecure"
      - "traefik.http.routers.whoami2.tls.certResolver=letsencrypt"
      - "traefik.http.routers.whoami2.rule=Host(`whoami.38c3.tschunk.social`) && Header(`x-auth-request-user`, `DragonHunter274`)"
      - "traefik.http.routers.whoami2.middlewares=oauth2-auth@file"
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
    volumes:
      - radarr-data:/config
      - /slow/media/radarr-out:/out
      - shared-download:/download
    ports:
      - 7676:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entryPoints=websecure"
      - "traefik.http.routers.radarr.tls.certResolver=letsencrypt"
      - "traefik.http.routers.radarr.rule=Host(`radarr.38c3.tschunk.social`)" # Edit here to change the domain name
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.middlewares=oauth2-auth@file"

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/paris
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=organizr
    volumes:
      - sonarr-data:/config
      - /slow/media/sonarr-out:/out
      - shared-download:/download
    ports:
      - 7878:7878
      - 8989:8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entryPoints=websecure"
      - "traefik.http.routers.sonarr.tls.certResolver=letsencrypt"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.38c3.tschunk.social`)" # Edit here to change the domain name
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.port=8989"
      - "traefik.http.routers.sonarr.middlewares=oauth2-auth@file"
    restart: unless-stopped
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/paris
    volumes:
      - prowlarr-data:/config
    ports:
      - 9696:9696
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entryPoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certResolver=letsencrypt"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.38c3.tschunk.social`)" # Edit here to change the domain name
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.middlewares=oauth2-auth@file"
    restart: unless-stopped
  vsftpd:
    image: metabrainz/docker-anon-ftp
    container_name: ftpserver
    volumes:
      - /upload:/var/ftp/
    ports:
      - "21:21"
      - "20:20"
      - "65500-65515:65500-65515"
    environment:
      PASV_ADDRESS: "151.217.62.81"
      FTPD_BANNER: "Welcome to the Faboulous FTP Server! be gentle pls!"
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
#    ports:
#      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - qbittorrent-data:/config
      - shared-download:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.entryPoints=websecure"
      - "traefik.http.routers.torrent.tls.certResolver=letsencrypt"
      - "traefik.http.routers.torrent.rule=Host(`torrent.38c3.tschunk.social`)" # Edit here to change the domain name
      - "traefik.http.services.torrent.loadbalancer.server.port=8080"
      - "traefik.port=8080"
      - "traefik.http.routers.torrent.middlewares=oauth2-auth@file"


  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: "oauth2-proxy"
    environment:
      OAUTH2_PROXY_PROVIDER: "github"
      OAUTH2_PROXY_CLIENT_ID: "Ov23liKH7rfJBxmBN0vI"  # Replace with your GitHub Client ID
      OAUTH2_PROXY_CLIENT_SECRET: "99e4c67b304b2f7147926e29fa602507358a7ccc"  # Replace with your GitHub Client Secret
      OAUTH2_PROXY_COOKIE_SECRET: "acVnYPFTRTdvZ2ypgAKaTmBLy_isCpE9dH6FGLNbgBo="  # Replace with the generated cookie secret
      OAUTH2_PROXY_REDIRECT_URL: "https://oauth2.38c3.tschunk.social/oauth2/callback"
      OAUTH2_PROXY_COOKIE_DOMAINS: ".38c3.tschunk.social"
      OAUTH2_PROXY_WHITELIST_DOMAINS: ".38c3.tschunk.social"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_UPSTREAMS: "static://202"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_GITHUB_ORG: "fablabmuc-38c3"  # Optional: use GitHub orgs/teams for access control
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: "true"
#      OAUTH2_PROXY_SCOPE: "user:email read:user read:org"
    ports:
      - "4180:4180"
    command:
      - --http-address=0.0.0.0:4180
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.oauth2.rule=Host(`oauth2.38c3.tschunk.social`)"
      - "traefik.http.routers.oauth2.rule=(Host(`oauth2.38c3.tschunk.social`) && PathPrefix(`/oauth2/`)) || (PathPrefix(`/oauth2/`))"
      - "traefik.http.routers.oauth2.entrypoints=websecure"
      - "traefik.http.routers.oauth2.tls=true"
      - "traefik.http.routers.oauth2.tls.certResolver=letsencrypt"
      - "traefik.http.services.oauth2.loadbalancer.server.port=4180"

volumes:
  shared-download:
    driver: local
    driver_opts:
      type: none
      device: /flash/downloads
      o: bind
  radarr-data:
  sonarr-data:
  prowlarr-data:
  qbittorrent-data:
